[tools]
taplo = "latest"
uv = "latest"
ruff = "latest"
"pipx:djlint" = "latest"
bun = 'latest'

[env]
_.file = ".env"
_.path = ['{{config_root}}/node_modules/.bin']
ERP_DEBUG = true

[tasks]
manage = "uv run manage.py"
update = ["mise upgrade", "uv sync -U", "bun update"]
clean = "rm -rf node_modules .venv"
dev = "uv run manage.py tailwind runserver"
bundle = "bun build ./static/src/main.ts --outdir ./static/dist --watch"

[hooks]
postinstall = ["uv sync", "bun install"]

[settings]
experimental = true
python.uv_venv_auto = true
