[tools]
taplo = "latest"
uv = "latest"
ruff = "latest"
"pipx:djlint" = "latest"
bun = 'latest'
"ubi:F1bonacc1/process-compose" = "latest"

[env]
_.file = ".env"
ERP_DEBUG = true

[tasks]
update = ["mise upgrade", "uv sync -U", "bun update"]
clean = "rm -rf node_modules .venv"
manage = "uv run manage.py"
dev = "process-compose"
bundle = "bun build ./static/src/main.ts --outdir ./static/dist --watch"

[hooks]
postinstall = ["uv sync", "bun install"]

[settings]
experimental = true
python.uv_venv_auto = true
