[tools]
uv = "latest"
bun = 'latest'
"ubi:F1bonacc1/process-compose" = "latest"

[env]
_.file = ".env"
ERP_DEBUG = true

[tasks]
update = ["mise upgrade", "uv sync -U", "bun update"]
clean = "rm -rf node_modules .venv"
manage = "uv run manage.py"
dev = "process-compose"
bundle = "bun build ./static/src/main.ts --outdir ./static/dist --watch"
format = { alias = "fmt", run = [
  "ruff format -q .",
  "taplo format .",
  "djlint --reformat --quiet .",
] }
lint =  [
  "ruff check --fix .",
  "taplo lint .",
  "djlint --lint ."
]

[hooks]
postinstall = ["uv sync", "bun install"]

[settings]
experimental = true
python.uv_venv_auto = true
