[tools]
bun = "latest"
uv = "latest"
"ubi:F1bonacc1/process-compose" = "latest"

[hooks]
postinstall = ['uv sync --directory ./backend/', 'bun install --cwd=./web/']

[tasks]
update = ['uv sync --upgrade --directory ./backend/', 'bun update --cwd=./web/']
manage = "uv run ./backend/manage.py"
dev = "process-compose"
lint = ["mise run lint_backend", "mise run lint_web"]

[tasks.format]
alias = "fmt"
run = ["mise run format_backend"]

[tasks.format_backend]
hide = true
dir = "{{ config_root }}/backend/"
run = "uv run ruff format ."

[tasks.lint_backend]
hide = true
dir = "{{ config_root }}/backend/"
run = "uv run ruff check ."


[tasks.lint_web]
hide = true
dir = "{{ config_root }}/web/"
run = "bun lint"

[settings]
experimental = true
python.uv_venv_auto = true
pipx.uvx = true
