[tools]
bun = "latest"
uv = "latest"
"ubi:F1bonacc1/process-compose" = "latest"
age = "latest"
sops = "latest"
ruff = "latest"
taplo = "latest"

[env]
_.file = ".env.json"

DJANGO_DEBUG = true
NODE_ENV = "{{ env.NODE_ENV | default(value='development') }}"
DJANGO_FRONTEND_URL = "http://localhost:5173"

[hooks]
postinstall = ['uv sync --directory ./backend/', 'bun install']

[tasks]
update = ['uv sync --upgrade --directory ./backend/', 'bun update']
dev = "process-compose"
lint = ["taplo lint", "ruff check .", "bun run lint"]
format = ['taplo format', "ruff format .", "bun run lint:fix"]
generate_secret_key = "uv run --with django python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
edit_secrets = "sops edit .env.json"

[tasks.manage]
dir = "{{ config_root }}/backend"
run = "uv run ./manage.py"

[settings]
experimental = true

pipx.uvx = true
