[tools]
taplo = "latest"
uv = "latest"
ruff = "latest"
"pipx:djlint/djlint" = "latest"
bun = "latest"
"pipx:maturin" = "latest"
cargo = "latest"

[env]
_.file = ".env"
_.path = ['{{config_root}}/node_modules/.bin']
ERP_DEBUG = true

[settings]
experimental = true
python.uv_venv_auto = true
npm.bun = true
