[tools]
bun = "latest"
uv = "latest"
"ubi:F1bonacc1/process-compose" = "latest"
age = "latest"
sops = "latest"

[env]
_.file = ".env.json"
DJANGO_DEBUG = true
NODE_ENV = "{{ env.NODE_ENV | default(value='development') }}"

[hooks]
postinstall = ['uv sync --directory ./backend/', 'bun install --cwd=./web/']

[tasks]
update = ['uv sync --upgrade --directory ./backend/', 'bun update --cwd=./web/']
dev = "process-compose"
lint = ["mise run lint_backend", "mise run lint_web"]
generate_secret_key = "uv run --with django python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
edit_secrets = "sops edit .env.json"

[tasks.manage]
run = "uv run ./manage.py"
dir = "{{ config_root }}/backend"

[tasks.format]
alias = "fmt"
run = ["mise run format_backend"]

[tasks.format_backend]
hide = true
dir = "{{ config_root }}/backend/"
run = "uv run ruff format ."

[tasks.lint_backend]
hide = true
dir = "{{ config_root }}/backend/"
run = "uv run ruff check ."


[tasks.lint_web]
hide = true
dir = "{{ config_root }}/web/"
run = "bun lint"

[settings]
experimental = true
pipx.uvx = true
