[project]
name = "erp-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["django>=5.2", "environs[django]>=14.1.1"]

[dependency-groups]
dev = ["django-stubs>=5.1.3", "ruff>=0.11.4"]
